// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_h7Eo0Ei1P",
    "aws_user_pools_web_client_id": "22gpg8g8p1llisctlqsfpvuj8j",
    "oauth": {}
};


export default awsmobile;
